### ISSUE TITLE
&& not picking up syntax coloring in this specific circumstance

### ISSUE THREAD

**Issue by gbasood** [PJB3005/atomic-dreams#1]
``` DM
if(!cure_present && prob(stage_prob) && age > stage_minimum_age) //now the disease shouldn't get back up to stage 4 in no time
```

Even github syntax seems to reproduce this
https://github.com/gbasood/vgstation13/blob/d8e3c2d9b32d521868b1abd9ccace704e6536722/code/datums/disease.dm#L68

**Comment by PJB3005** [comment]
Operators actually need word bounds around them, I should remove that though since it's a dumb rule.

**Comment by PJB3005** [comment]
Fixed
